<?php
/**
 * Created by PhpStorm.
 * User: E
 * Date: 11.09.2018
 * Time: 16:02
 */

namespace AppBundle\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MenuCategoryMealType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("mealname", TextType::class, ["label" => "Nazwa dania"])
            ->add("mealdescription", TextareaType::class, ["label" => "Opis dania"])
            ->add('imageid', EntityType::class, [
                'class' => 'AppBundle:Images',
                'choice_label' => 'imgname',
                'label' => 'Zdjęcie z bazy',])
            ->add("price", TextType::class, ["label" => "Cena"])
            ->add("submit", SubmitType::class, ["label" => "Zapisz"]);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}